redis:
  database: 0
  host: 47.101.58.198
  port: 6379
  jedis:
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 20
      # 连接池中的最大空闲连接
      max-idle: 20
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 60s